FROM node:18

WORKDIR /app

# Copy all files (including schema.prisma) before install
COPY . .

# Install dependencies (postinstall will now succeed)
RUN npm install

# Expose backend port
EXPOSE 5004

CMD ["npm", "start"]
